#!/bin/bash

cat trunc_tls_oracles_lib.pvl > result_trunc_tls_oracles.pv

proof_file="proof_lemma_${1}.pv" 
#echo "$proof_file"
cat $proof_file >> result_trunc_tls_oracles.pv

cat lib_for_prf.pv >> result_trunc_tls_oracles.pv
cat trunc_tls_clnt_oracles.pv >> result_trunc_tls_oracles.pv
cat trunc_serv_tls_oracles.pv >> result_trunc_tls_oracles.pv
./../cryptoverif result_trunc_tls_oracles.pv
